import { Octokit } from "octokit";
import { Repository } from "../types";
import { generateEpitaph } from "./epitaphs";

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN,
});

export async function getAllRepos(username: string): Promise<Repository[]> {
  try {
    const { data } = await octokit.request("GET /users/{username}/repos", {
      username,
      sort: "updated",
      direction: "desc",
      per_page: 20, // Focus on top 20
    });

    let filtered = data.filter((repo) => !repo.fork);

    // MOCK DATA FALLBACK
    // If we still have nothing (API error, rate limit, or fresh user), return fake data
    // so the user can verify the design.
    if (!filtered || filtered.length === 0) {
      console.log("⚠️ API returned empty. Switching to MOCK DATA.");
      return [
        {
          id: 1,
          name: "BURNT_MIX_2003",
          description:
            "Summer vibes and broken dreams. Low bit-rate mp3s included.",
          html_url: "https://github.com",
          pushed_at: "2003-08-15T00:00:00Z",
          created_at: "2003-05-10T00:00:00Z",
          language: "MP3",
          stargazers_count: 50,
          topics: ["mixtape", "2003"],
          epitaph: "The soundtrack to a summer that never ended.",
        },
        {
          id: 2,
          name: "FINAL_PROJECT_FINAL",
          description:
            "This one is ACTUALLY final. No more edits. For real this time.",
          html_url: "https://github.com",
          pushed_at: "2023-12-24T00:00:00Z",
          created_at: "2023-09-01T00:00:00Z",
          language: "TypeScript",
          stargazers_count: 1,
          topics: ["thesis", "final"],
          epitaph: "Final meant 'until I found another bug'.",
        },
        {
          id: 3,
          name: "DO_NOT_DELETE_2",
          description:
            "Seriously do not. The entire server hangs on this script.",
          html_url: "https://github.com",
          pushed_at: "2021-04-12T00:00:00Z",
          created_at: "2021-01-01T00:00:00Z",
          language: "Python",
          stargazers_count: 0,
          topics: ["critical", "legacy"],
          epitaph: "A load-bearing comment in a sea of technical debt.",
        },
        {
          id: 4,
          name: "THESIS_BACKUP_BACKUP",
          description: "V3 of the backup of the original copy.",
          html_url: "https://github.com",
          pushed_at: "2020-05-20T00:00:00Z",
          created_at: "2019-11-01T00:00:00Z",
          language: "LaTeX",
          stargazers_count: 0,
          topics: ["academia", "anxiety"],
          epitaph: "Redundancy is the only cure for imposter syndrome.",
        },
        {
          id: 5,
          name: "abandoned-game-engine",
          description: "C++ engine because Unity wasn't 'optimized' enough.",
          html_url: "https://github.com",
          pushed_at: "2022-05-12T00:00:00Z",
          created_at: "2022-01-01T00:00:00Z",
          language: "C++",
          stargazers_count: 0,
          topics: ["gamedev"],
          epitaph: "Premature optimization is the root of all abandoned repos.",
        },
        {
          id: 6,
          name: "failed-startup-idea",
          description:
            "Uber for toasters. Disrupted nothing but sleep schedules.",
          html_url: "https://github.com",
          pushed_at: "2023-01-01T00:00:00Z",
          created_at: "2023-01-01T00:00:00Z",
          language: "C#",
          stargazers_count: 2,
          topics: ["startup"],
          epitaph: "Disrupted nothing but your bank account.",
        },
        {
          id: 7,
          name: "crypto-trading-bot",
          description: "Lost $500 in 15 minutes. It was high frequency.",
          html_url: "https://github.com",
          pushed_at: "2021-11-20T00:00:00Z",
          created_at: "2021-11-01T00:00:00Z",
          language: "Go",
          stargazers_count: 0,
          topics: ["crypto", "regret"],
          epitaph: "HODLing onto this codebase forever.",
        },
        {
          id: 8,
          name: "my-first-blog",
          description: "Gatsby v2 survivor. Waiting for a rewrite.",
          html_url: "https://github.com",
          pushed_at: "2021-08-20T00:00:00Z",
          created_at: "2021-01-01T00:00:00Z",
          language: "JavaScript",
          stargazers_count: 1,
          topics: ["blog"],
          epitaph: "A static site for a static developer.",
        },
        {
          id: 9,
          name: "linux-kernel-patch-attempt",
          description: "Got rejected by Linus in 30 seconds.",
          html_url: "https://github.com",
          pushed_at: "2018-03-01T00:00:00Z",
          created_at: "2018-02-28T00:00:00Z",
          language: "C",
          stargazers_count: 0,
          topics: ["kernel", "shame"],
          epitaph: "The only thing more brittle than the kernel was my ego.",
        },
        {
          id: 10,
          name: "jquery-spaghetti-monster",
          description: "The legacy project that won't die.",
          html_url: "https://github.com",
          pushed_at: "2015-10-10T00:00:00Z",
          created_at: "2014-01-01T00:00:00Z",
          language: "jQuery",
          stargazers_count: 0,
          topics: ["legacy", "monstrosity"],
          epitaph: "Selectors within selectors, world without end.",
        },
        {
          id: 11,
          name: "unreleased-ios-app",
          description: "Waiting for Apple to approve a flashlight app.",
          html_url: "https://github.com",
          pushed_at: "2010-06-01T00:00:00Z",
          created_at: "2010-01-01T00:00:00Z",
          language: "Objective-C",
          stargazers_count: 0,
          topics: ["mobile"],
          epitaph: "Rejected for 'minimum functionality' - rightfully so.",
        },
        {
          id: 12,
          name: "perl-script-from-2005",
          description: "Regular expressions that look like static.",
          html_url: "https://github.com",
          pushed_at: "2005-01-01T00:00:00Z",
          created_at: "2004-12-01T00:00:00Z",
          language: "Perl",
          stargazers_count: 0,
          topics: ["perl", "noise"],
          epitaph: "Taint mode: enabled. Career hope: disabled.",
        },
        {
          id: 13,
          name: "flash-website-v4",
          description: "Cinematic intro that takes 5 minutes to load.",
          html_url: "https://github.com",
          pushed_at: "2009-12-01T00:00:00Z",
          created_at: "2009-01-01T00:00:00Z",
          language: "ActionScript",
          stargazers_count: 10,
          topics: ["flash", "nostalgia"],
          epitaph: "The death of a player. The birth of a memory.",
        },
        {
          id: 14,
          name: "sql-injection-playground",
          description: "DROP TABLE users; --",
          html_url: "https://github.com",
          pushed_at: "2016-12-01T00:00:00Z",
          created_at: "2016-01-01T00:00:00Z",
          language: "PHP",
          stargazers_count: 0,
          topics: ["security", "fail"],
          epitaph: "Who is Little Bobby Tables and why is he here?",
        },
        {
          id: 15,
          name: "unfunny-irc-bot",
          description: "Tells jokes that only I find funny.",
          html_url: "https://github.com",
          pushed_at: "2002-01-01T00:00:00Z",
          created_at: "2001-01-01T00:00:00Z",
          language: "Python",
          stargazers_count: 0,
          topics: ["irc", "humor"],
          epitaph: "Kicked for spamming. Forgotten for existing.",
        },
        {
          id: 16,
          name: "css-grid-experiment-v12",
          description: "Finally centered a div.",
          html_url: "https://github.com",
          pushed_at: "2018-05-01T00:00:00Z",
          created_at: "2018-01-01T00:00:00Z",
          language: "CSS",
          stargazers_count: 5,
          topics: ["css", "centering"],
          epitaph: "Centered the div, lost the plot.",
        },
        {
          id: 17,
          name: "rust-learning-repo",
          description: "Borrow checker turned into a collection agent.",
          html_url: "https://github.com",
          pushed_at: "2024-11-01T00:00:00Z",
          created_at: "2024-10-01T00:00:00Z",
          language: "Rust",
          stargazers_count: 0,
          topics: ["rust", "learning"],
          epitaph: "The lifetime of this repo was shorter than its types.",
        },
        {
          id: 18,
          name: "vba-excel-macro-hell",
          description: "The reason the accounting department cried.",
          html_url: "https://github.com",
          pushed_at: "2012-01-01T00:00:00Z",
          created_at: "2011-01-01T00:00:00Z",
          language: "VBA",
          stargazers_count: 0,
          topics: ["office", "horror"],
          epitaph: "A spreadsheet that became a religion.",
        },
        {
          id: 19,
          name: "ai-hype-wrapper",
          description: "10 lines of code calling OpenAI.",
          html_url: "https://github.com",
          pushed_at: "2024-05-01T00:00:00Z",
          created_at: "2024-04-01T00:00:00Z",
          language: "TypeScript",
          stargazers_count: 0,
          topics: ["ai", "hype"],
          epitaph: "Prompt engineering is just polite yelling.",
        },
        {
          id: 20,
          name: "THE_BURNT_ARCHIVES_V1",
          description: "Where it all began. The recursive archive.",
          html_url: "https://github.com",
          pushed_at: "2025-12-24T00:00:00Z",
          created_at: "2025-12-20T00:00:00Z",
          language: "TypeScript",
          stargazers_count: 100,
          topics: ["archive", "autonomous"],
          epitaph: "Burnt into the history of this machine.",
        },
      ];
    }

    return await Promise.all(
      filtered.map(async (repo) => ({
        id: repo.id,
        name: repo.name,
        description: repo.description ?? null,
        html_url: repo.html_url,
        pushed_at: repo.pushed_at ?? null,
        created_at: repo.created_at ?? null,
        language: repo.language ?? null,
        stargazers_count: repo.stargazers_count ?? 0,
        topics: repo.topics || [],
        epitaph: await generateEpitaph(repo.name, repo.description ?? null),
      }))
    );
  } catch (error) {
    console.error("Error fetching repos:", error);
    // Return mock data on crash too
    return [
      {
        id: 99,
        name: "api-error-log",
        description: "System failed to fetch real data. Enjoy this simulation.",
        html_url: "#",
        pushed_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        language: "System",
        stargazers_count: 404,
        topics: ["error"],
        epitaph: "Even the API gave up on you.",
      },
    ];
  }
}
